### ISSUE TITLE
Run the generated tests in different environments (e.g. development, stage, and production)

### ISSUE THREAD

**Issue by marcredhat** [ponicode/unit-testing-action#1]
Hi,

Great work on Ponicode!
I'd like to understand how to:
1)  run the generated tests in different environments (e.g. development, stage, and production).
Please see a short video on 
how to deploy a React App with an Express Backend on OpenShift 4.5 and 
monitor it with Dynatrace at 
https://www.youtube.com/watch?v=yTq0NCdASCU

See also: https://developers.redhat.com/blog/2020/04/28/contract-first-development-create-a-mock-back-end-for-realistic-data-interactions-with-react/

2) if generated tests can be used for health monitoring (e.g. by detecting that a mocha test timeouts in an environment,  returns an error code, runs too slowly etc). If yes, could we send these metrics to, say, Dynatrace?

3) OpenShift customers typically use source-to-image to build and deploy React and Node.js apps 
(please see 
https://www.openshift.com/blog/deploying-a-react-app-with-an-express-backend-on-openshift and https://developers.redhat.com/articles/deploy-a-NodeJS-app-OpenShift). 
So we should be able to deploy the app in dev, staging, prod etc environments/OpenShift namespaces with the same command and just use environment variables to 
specify where we want to run Ponicode tests. Thoughts?
NOTE: To install the Ponicode demo app on OpenShift 4.5, please see https://github.com/marcredhat/ponicode

4) Keptn could make everything even better as it allows workflow information to be decoupled from the tools that are used, i.e., whether it’s  Ponicode and JMeter tests in dev and 
Ponicode and a  Selenium test in staging.
(short video at https://bit.ly/340DbFb)

Thanks,
Marc

**Comment by bbouffaut** [comment]
Many thanks @marcredhat . As discussed during our call earlier, we are currently working on our Enterprise and Integration roadmap. OpenShift is definitively one of the integration we are thinking about. Let's keep in touch for further collaboration.
